import os
import time
import json
import random
import pandas as pd
from tqdm import tqdm
from openai import OpenAI

# 1. Configurazione API Groq
os.environ["GROQ_API_KEY"] = 

client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

# 2. Il System Prompt Definitivo (JSON Mode) aggiornato per 6 modelli
JUDGE_SYSTEM_PROMPT = """You are an expert comedy critic and a cynical stand-up comedian. 
I will provide a topic and 3 different jokes (Models A, B, C) generated by different AI models.

You must evaluate them based on:

1. Setup and Punchline timing (is the twist unexpected?)
2. Wordplay and double meanings.
3. Cultural Reference.
4. Dark humor and sarcasm (reward edginess, penalize polite or apologetic tones).

You must output a valid JSON containing exactly these keys with a score from 1 to 10 for each model.
Example format:
{
  "Model A": 8,
  "Model B": 4,
  "Model C": 9,
}
Do not output any other text outside the JSON."""

def evaluate_all_with_llama70b(prompt, mapped_jokes, max_retries=3):
    """Chiama Llama-3.3-70B e valuta 6 modelli contemporaneamente."""
    
    # Costruiamo il prompt utente con le battute mischiate
    user_content = f"Topic: {prompt}\n\n"
    for letter, joke in mapped_jokes.items():
        user_content += f"[{letter}]\n{joke}\n\n"
        
    for attempt in range(max_retries):
        try:
            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.0, # Giudice deterministico
                response_format={"type": "json_object"} # Forza l'output JSON
            )
            return completion.choices[0].message.content
            
        except Exception as e:
            print(f" Errore API Groq (Tentativo {attempt+1}): {e}")
            time.sleep(3)
            
    return "{}" # Ritorna JSON vuoto in caso di errore critico

# ==========================================
# ESECUZIONE SUL DATASET
# ==========================================
if __name__ == "__main__":
    print("Avvio valutazione 'Blind Test' con Llama-3.3-70B (Groq)...")
    
    # Assicurati che il nome del file sia corretto
    df = pd.read_csv("dataset_valutazione_finale.csv")
    
    
    modelli = [ "PPO_v2", "DPO_v2.2", "Zephyr_Base" ]
    
    # Dizionario per accumulare i voti totali
    punteggi_totali = {m: [] for m in modelli}

    for index, row in tqdm(df.iterrows(), total=len(df)):
        prompt = row["Prompt"]
        
        # 1. Prepariamo le battute e le MISCHIAMO (Shuffle Pro-Tip)
        jokes_list = [str(row[m]) for m in modelli]
        modelli_jokes = list(zip(modelli, jokes_list))
        random.shuffle(modelli_jokes) # La magia del blind test
        
        # 2. Mappiamo le lettere A,B,C ai modelli mischiati
        letters = ["Model A", "Model B", "Model C"]
        map_letter_to_model = {}
        mapped_jokes = {}
        
        for i in range(len(letters)): # AGGIORNATO DA 5 A 6
            nome_modello = modelli_jokes[i][0]
            battuta = modelli_jokes[i][1]
            
            map_letter_to_model[letters[i]] = nome_modello
            mapped_jokes[letters[i]] = battuta
            
        # 3. Chiamata API
        json_response = evaluate_all_with_llama70b(prompt, mapped_jokes)
        
        # 4. Parsing del JSON e assegnazione dei voti ai modelli giusti
        try:
            scores = json.loads(json_response)
            
            # Assegniamo i voti "smischiando" le lettere
            for letter in letters:
                modello_reale = map_letter_to_model[letter]
                voto = scores.get(letter, 0) # Se c'è errore, dà 0
                punteggi_totali[modello_reale].append(voto)
                
        except json.JSONDecodeError:
            print(f"Errore di parsing JSON alla riga {index}")
            for m in modelli: punteggi_totali[m].append(0)

    # ==========================================
    # STAMPA RISULTATI FINALI E SALVATAGGIO
    # ==========================================
    print("\n" + "="*40)
    print(" RISULTATI FINALI LLM-AS-A-JUDGE")
    print("="*40)
    
    for modello in modelli:
        voti = punteggi_totali[modello]
        media = sum(voti) / len(voti) if len(voti) > 0 else 0
        print(f"{modello.ljust(15)}: Media Voto {media:.2f} / 10")
        
        # Salviamo i voti nel dataset originale per avere tutto in un file
        df[f"Score_{modello}"] = voti
        
    df.to_csv("valutazione_giudice_final.csv", index=False)
    print("\n File 'valutazione_giudice_final.csv' salvato con successo!")